# Generated by Django 4.2.28 on 2026-02-16 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='destacados/', verbose_name='Imagen')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Destacado',
                'verbose_name_plural': 'Destacados',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='investigaciones/', verbose_name='Fotografía')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('url_doc', models.FileField(upload_to='documentos/', verbose_name='Documento PDF')),
                ('tags', models.CharField(choices=[('Riego y Drenaje', 'Riego y Drenaje'), ('Maquinaria Agrícola', 'Maquinaria Agrícola'), ('Poscosecha', 'Poscosecha'), ('Agroindustria', 'Agroindustria'), ('Tecnología', 'Tecnología'), ('Mecanización', 'Mecanización'), ('Hídrica', 'Hídrica')], max_length=50, verbose_name='Categoría')),
                ('titulo', models.CharField(default='', max_length=200, verbose_name='Título')),
                ('autores', models.CharField(default='', max_length=200, verbose_name='Autores')),
            ],
            options={
                'verbose_name': 'Investigación',
                'verbose_name_plural': 'Investigaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='noticias/', verbose_name='Fotografía')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('titulo', models.CharField(default='', max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(default='NOTICIA', max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Suscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Suscripción')),
            ],
            options={
                'verbose_name': 'Suscrito',
                'verbose_name_plural': 'Suscritos',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
    ]
