# Generated by Django 4.2.28 on 2026-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_proyectos', models.IntegerField(default=15, help_text='Número de proyectos completados', verbose_name='Cantidad de Proyectos')),
                ('cantidad_miembros', models.IntegerField(default=40, help_text='Número de miembros del semillero', verbose_name='Cantidad de Miembros')),
                ('cantidad_publicaciones', models.IntegerField(default=8, help_text='Número de publicaciones científicas', verbose_name='Cantidad de Publicaciones')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
